# Personal Information
name: "Your Name"
title: "Full Stack Developer"
location: "Your City, Country"
email: "youremail@example.com"
phone: "+1234567890"
website: "https://yourwebsite.com"
linkedin: "https://www.linkedin.com/in/your-profile"
github: "https://github.com/yourusername"

# About Me
about:
  summary: >
    A passionate and dedicated full stack developer with experience in building
    web applications. I specialize in JavaScript and have a keen interest in
    learning new technologies to solve complex problems.

# Skills
skills:
  - category: "Languages"
    list:
      - "JavaScript"
      - "HTML5"
      - "CSS3"
      - "Python"
  - category: "Frameworks/Libraries"
    list:
      - "React.js"
      - "Node.js"
      - "Express.js"
      - "Vue.js"
      - "Bootstrap"
  - category: "Databases"
    list:
      - "MongoDB"
      - "MySQL"
      - "PostgreSQL"
  - category: "Tools/Technologies"
    list:
      - "Git"
      - "Webpack"
      - "Docker"
      - "Jenkins"
  - category: "Others"
    list:
      - "Agile Methodologies"
      - "RESTful APIs"
      - "Responsive Web Design"

# Projects
projects:
  - name: "Project 1"
    description: >
      A web application built with React.js for managing tasks and projects.
      It includes user authentication, real-time updates, and data visualization.
    technologies: ["React.js", "Node.js", "MongoDB"]
    github: "https://github.com/yourusername/project-1"
    demo: "https://project1demo.com"

  - name: "Project 2"
    description: >
      An e-commerce website developed using Vue.js and Express.js. It features
      product browsing, cart management, and secure payment processing.
    technologies: ["Vue.js", "Express.js", "MongoDB"]
    github: "https://github.com/yourusername/project-2"
    demo: "https://project2demo.com"

# Contact Information
contact:
  linkedin: "https://www.linkedin.com/in/your-profile"
  github: "https://github.com/yourusername"
  email: "youremail@example.com"
